repos:
  - repo: https://github.com/jazzband/pip-tools
    rev: "7.4.1"
    hooks:
      - id: pip-compile
        name: Recompile requirements.txt
        args: ["requirements.in"]
        additional_dependencies: ["pip-tools"]
        language: python

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files